[package]
name = "first-rpi-test"
version = "0.1.0"
edition = "2024"

[dependencies]
axum = "0.8.8"
rppal = "0.22.1"
serde = { version = "1.0.228", features = ["derive"] }
simple-signal = "1.1.1"
tokio = { version = "1.48.0", features = ["full"] }
ws2818-rgb-led-spi-driver = "2.0.0"
